language: java
before_deploy:
- echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
deploy:
  provider: script
  script: bash scripts/deploy.sh
  skip_cleanup: true
  on:
    all_branches: true
