version: "3"
services:
  turniere:
    image: turniere/turniere-website:latest
    ports:
    - 8080:8080
    volumes:
    - ./src/main/resources/application.yml:/home/turniere/application.yml
    links:
    - postgres:postgres

  postgres:
    image: postgres:11-alpine
    ports:
    - 5432:5432
    environment:
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=turniere

  mailhog:
    image: mailhog/mailhog
    ports:
    - 8025:8025
    - 1025:1025
