spring:
  root_url: http://localhost:8080
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties.hibernate.temp.use_jdbc_metadata_defaults: false

  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/turniere
    username: postgres
    password: password

  thymeleaf:
    cache: false

  mail:
    subject: turnie.re Registrierung - Du hast es fast geschafft!
    textPath: src/main/resources/mail.txt
    host: mailhog
    from: registration@turnie.re
    properties.mail:
      transport.protocol: smtp
      smtp.port: 1025
