spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties.hibernate.temp.use_jdbc_metadata_defaults: false

  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url:
    username:
    password:

  thymeleaf:
    cache: false